name: Upload and set public access to a file in S3

on:
  workflow_dispatch:
    inputs:
      bucket_name:
        description: 'S3 Bucket name'
        required: true
      file_path:
        description: 'Local file path to be uploaded'
        required: true
      s3_key:
        description: 'S3 Object key including file name'
        required: true

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  AWS_REGION: 'us-east-1' 

jobs:
  upload_to_s3:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Disable block public access settings on S3 bucket (Be cautious!)
        run: |
          aws s3api put-public-access-block \
            --bucket ${{ github.event.inputs.bucket_name }} \
            --public-access-block-configuration "BlockPublicAcls=false,IgnorePublicAcls=false,BlockPublicPolicy=false,RestrictPublicBuckets=false"
        continue-on-error: true # Continue if the bucket already has these settings

      - name: Upload file to S3 and set public-read ACL
        run: aws s3 cp ${{ github.event.inputs.file_path }} s3://${{ github.event.inputs.bucket_name }}/${{ github.event.inputs.s3_key }} --acl public-read
