name: Upload to S3

on:
  workflow_dispatch:
    inputs:
      bucket_name:
        description: 'S3 bucket name'
        required: true
      folder_name:
        description: 'Name of the folder in S3'
        required: true
      source_dir:
        description: 'Path to the directory containing files to upload'
        required: true
      file_name:
        description: 'Name of the file to be included'
        required: true

jobs:
  upload:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      
      - name: Filter Files
        id: filter_files
        run: |
          echo "::set-output name=file_path::${{ github.event.inputs.source_dir }}/${{ github.event.inputs.file_name }}"
      
      - name: Upload to S3
        uses: shallwefootball/s3-upload-action@master
        with:
          aws_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws_bucket: ${{ github.event.inputs.bucket_name }}
          source: ${{ steps.filter_files.outputs.file_path }}
          destination_dir: '${{ github.event.inputs.folder_name }}/'
