name: Normalize destination path

on:
  workflow_dispatch:
    inputs:
      destination_path:
        description: 'Destination path in the S3 bucket'
        required: true

jobs:
  normalize_path:
    runs-on: ubuntu-latest
    steps:
      - name: Remove trailing backslashes
        run: |
          normalized_path=$(echo "${{ github.event.inputs.destination_path }}" | sed 's/\\$//')
          echo "::set-output name=normalized_destination_path::$normalized_path"

      - name: Upload a file from Assets to S3
        uses: prewk/s3-cp-action@v2
        with:
          aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          source: '${{ github.workspace }}/assets/${{ github.event.inputs.file_name }}'
          dest: 's3://${{ github.event.inputs.bucket_name }}/${{ steps.normalize_path.outputs.normalized_destination_path }}/${{ github.event.inputs.file_name }}'
        env:
          flags: '--acl public-read --metadata=Cache-Control=86400'
