name: Upload a file from Assets to S3

on:
  workflow_dispatch:
    inputs:
      bucket_selection:
        description: 'Select the S3 bucket'
        required: true
        type: choice
        options:
          - konvokubeace1
          - konvokubeace2
          - konvokubeace3
      destination_path:
        description: 'Destination path in the S3 bucket'
        required: true
      file_name:
        description: 'Name of the file to upload from the "assets" directory'
        required: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up AWS CLI
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
         

      - name: Process destination path
        id: path
        run: |
          destination_path="${{ github.event.inputs.destination_path }}"
          destination_path_trimmed=$(echo "$destination_path" | sed 's:/*$::') # Removes trailing slashes
          echo "DEST_PATH=$destination_path_trimmed" >> $GITHUB_ENV

      - name: Upload file to S3 with public-read acl
        run: |
          aws s3api put-object --bucket ${{ github.event.inputs.bucket_selection }} --key ${{ env.DEST_PATH }}/${{ github.event.inputs.file_name }} --body ./assets/${{ github.event.inputs.file_name }} --acl public-read
