name: Upload a file from Assets to S3

on:
  workflow_dispatch:
    inputs:
      bucket_selection:
        description: 'Select the S3 bucket'
        required: true
        type: choice
        options:
          - konvokubeace1
          - konvokubeace2
          - konvokubeace3
      destination_path:
        description: 'Destination path in the S3 bucket'
        required: true
      file_name:
        description: 'Name of the file to upload from the "assets" directory'
        required: true

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  AWS_DEFAULT_REGION: 'us-east-1' # N. Virginia region

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Process destination path
        run: |
          destination_path="${{ github.event.inputs.destination_path }}"
          destination_path_trimmed=$(echo "$destination_path" | sed 's:/*$::') # Removes trailing slashes
          echo "DESTINATION_PATH_TRIMMED=${destination_path_trimmed}" >> $GITHUB_ENV

      - name: Upload file to S3 and set public-read ACL
        run: aws s3 cp ./assets/${{ github.event.inputs.file_name }} s3://${{ github.event.inputs.bucket_selection }}/${{ env.DESTINATION_PATH_TRIMMED }}/${{ github.event.inputs.file_name }} --acl public-read
