name: Upload a folder to S3

on:
  workflow_dispatch:
    inputs:
      source_directory:
        description: 'Path to the local directory to upload'
        required: true
      bucket_name:
        description: 'Name of the S3 bucket'
        required: true
      destination_path:
        description: 'Destination path in the S3 bucket'
        required: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    
    - name: Copy a folder to S3
      uses: prewk/s3-cp-action@v2
      with:
        aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        source: ${{ github.event.inputs.source_directory }}
        dest: 's3://${{ github.event.inputs.bucket_name }}/${{ github.event.inputs.destination_path }}'
        
