name: Upload to S3

on:
  push:
    branches:
      - main  # Adjust this according to your branch name

jobs:
  upload:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: shallwefootball/s3-upload-action@master
        with:
          aws_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY}}
          aws_bucket: mysusharibucket
          aws_region: us-east-1
          source_dir: 'assets'
