name: Upload a file from Assets to S3

on:
  workflow_dispatch:
    inputs:
      endpoint_selection:
        description: 'Select the endpoint'
        required: true
        type: choice
        options:
          - static.ta.com
          - assets.tal.com
      destination_path:
        description: 'Destination path in the S3 bucket'
        required: true
      file_name:
        description: 'Name of the file to upload from the "assets" directory'
        required: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup bucket based on endpoint selection
        run: |
          if [ "${{ github.event.inputs.endpoint_selection }}" == "static.ta.com" ]; then
            echo "BUCKET_NAME=s3proxy.ta.com" >> $GITHUB_ENV
          else
            echo "BUCKET_NAME=talassets" >> $GITHUB_ENV
          fi

      - name: Process destination path
        run: |
          destination_path="${{ github.event.inputs.destination_path }}"
          destination_path_trimmed=$(echo "$destination_path" | sed 's:^/*::' | sed 's:/*$::') # Removes leading and trailing slashes
          echo "destination_path_trimmed=$destination_path_trimmed" >> $GITHUB_ENV

      - name: Copy file to S3
        uses: prewk/s3-cp-action@v2
        with:
          aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          source: './assets/${{ github.event.inputs.file_name }}'
          dest: 's3://${{ env.BUCKET_NAME }}/${{ env.destination_path_trimmed }}/${{ github.event.inputs.file_name }}'
          flags: '--acl public-read-write'
